### ISSUE TITLE
Mqtt feature support

### ISSUE THREAD

**Issue by pissten** [seaky/nspanel_pro_tools_apk#10]
Hi,

Thanks for this great app! Would love to see a MQTT client feature, 
to be able to publish the sensor data by MQTT.
Then I could make automation in HA wake the NSpanel when proximity sensor gets triggered.
This is especially a use case for waking the Wallpanel app, when in screensaver mode.

**Comment by jj-uk** [comment]
The WallPanel app has MQTT and publishes the sensor states. Does this not work when the screensaver is active?

**Comment by pissten** [comment]
The wallpanel doesn't publish the proximity sensor, for the nspanel unfortunately. But I use the mqtt features of wallpanel for waking up the device, when i wave in front of the nspanel. I achieve this by using automatic app and mqtt plugin. Would be nice to have the mqtt in the nspanel_pro_tools though, so everything is handled from one app.
________________________________

**Comment by seaky** [comment]
So just to clarify you mean that if you wave in front of the panel you want to send some kind of MQTT message to trigger something eg light. Am I right?

**Comment by pissten** [comment]
Yes, that would be great 👌 if the nspanel_pro_tools were able to publish its sensors data, the same way that wallpanel does. But also include the proximity sensor. Would also be great if it could include settings for threshold variables, so that the output mqtt message could be sent as a binary_sensor for on/off trigger. ( This is how it's done by the automagic app today )
________________________________

**Comment by tom-lejeune** [comment]
I'm not sure if this belongs here or I need to make a new issue.  In current version, in the setup of MQTT, under publish events, I have the swipe gestures active, but in home assistant, the "touch" status is "unknown".  In the manual I see that this could be used in an automation, but I never get the MQTT status of the Gestures.

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: event.nspanel2_touch
            attribute: event_type
            **state: swipe_up**

![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/2422652/af01a5a5-4192-4ed0-9df4-9a9c76d89d6d)


Is this not working in the curent version 2.0 yet? (I would guess it works because it's in the manual)
thanks,
Tom

(ps, the wake up on wave works fine.  I was trying to configure an automation where I could wave left / right to sweep to next/previous dashboard with swipe_nav.
