### ISSUE TITLE
Screen Mirroring

### ISSUE THREAD

**Issue by peepshow-21** [seaky/nspanel_pro_tools_apk#29]
Hi,

A couple of things;

1. I just wondered if anyone has been able to get screen mirroring working in android studio? I get this.. 
![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/42150988/93e10494-81ee-4806-b98e-7aaa9356d87b)
for
![image](https://github.com/seaky/nspanel_pro_tools_apk/assets/42150988/c16a6f7a-bcbe-4f57-9fbe-cd795f5d14c2)

Since I enabled USB debugging (long ago). My device seem stuck on firmware 1.4. 

2. Is there an manual way to flash later firmware?
3. What is the latest firmware you can install where you can still your ADB over TCP?

Thanks

**Comment by seaky** [comment]
I don't understand why everyone wants to update to newer firmware. In every new firmware case, it's Android 8.1. Even the build number is the same. So simple no reason to update to newer firmware except if you want to go back to Sonoff mode. 

But if you unlock to OS via Sonoff official method you simply lost new serverside features by forever. Btw you can update by my tool to newer firmware but there is allways a risk to completely brick your device because if the new fw does not support adb and you unlock your device it will be useless.

Btw there is way more easy method to unlock the device without loosing any support forever.
