### ISSUE TITLE
Sleep is just dim and proximity does not brighten

### ISSUE THREAD

**Issue by haywiremk** [seaky/nspanel_pro_tools_apk#3]
I used this app instead of Automagic since looks to offer the same featureset + the autostart app.  However have a couple things not quite right

1) When you select active on you cannot select wake from touch to be on.  Why would anyone want any of the options off on the first screen?
2) second I have the sleep set to 30 seconds in settings and it dims the screen instead of shutting off.  However the proximity sensor does not brighten this screen.  Touching however does

Otherwise I have followed
Matt Watt Tech youtube video for setup.

**Comment by seaky** [comment]
Hi,

1. I have 3 devices and if the activate toggle is on I can turn on the touch toggle. Btw I in the first release I dont want to turn on resume on boot and touch feature because the touch implementation is very new so I wanted to wait for some feedbacks and the resume on boot also can cause some issues. But after some positive feedback I’ll make them default on.

2. There is something wrong in your configuration. Did you set the diplay off in the android settings menu? If you set it in the eWeLinkControlPanel app it is related to just app so it is wrong. And the reason why the touch wakes up from the dimmed state because it is a built in android feature. My app is running only if the screen is fully off. See the pervious issue there is the solution.

Regards,
Seaky

**Comment by haywiremk** [comment]
1)Yes if I turn of resume on boot the wake on touch can be selected.  There is weird logic here where active on/off I have to change to luanch app and back to select the lower toggles.
2)I did do the Setting->Display->Sleep.  However it is just dimming my screen for sleep not turning fully off.  I guess have to keep digging into why.

**Comment by seaky** [comment]
1) I’m gonna release a new version this week which uses a fully different “toggle logic” and new features
2)) Setting->Display->Sleep is wrong I assume that you set it in the eWelinkControl app. You have to use the Android Settings app Settings -> Display -> **Advanced** -> Sleep

**Comment by haywiremk** [comment]
Finally found the setting for this.  I never changed it so maybe some units come with this enabled. For others with this issue.  Will assume you already have enabled developer options.

1. Select Developer Options or "System," then "Advanced," then "Developer Options."
2. Toggle Stay Awake to disabled.

If you wanted you unit to dim and not sleep just enabled.  This options is for devices running on AC or external power.

**Comment by seaky** [comment]
Thanks for the response I'll add your finding to the manual. New version will use a very different toggle "philosophy".
Coming very soon...
